- hosts: local
  become: false

  vars:
    docker_image: "{{ docker_image | default('varshayamsani/scientificcalculator') }}"
    docker_tag:   "{{ docker_tag | default('latest') }}"
    container_name: Calculator

  tasks:
    - name: Pull latest docker image
      command: docker pull {{ docker_image }}:{{ docker_tag }}

    - name: Stop and remove old container (if any)
      shell: docker rm -f {{ container_name }} || true

    - name: Run new container
      shell: docker run -d --name {{ container_name }} -it --restart unless-stopped {{ docker_image }}:{{ docker_tag }}
