- hosts: localhost
  become: false

  vars:
    docker_image: varshayamsani/scientificcalculator
    docker_tag: latest
    container_name: Calculator

  tasks:
    - name: Pull latest docker image
      command: docker pull {{ docker_image }}:{{ docker_tag }}

    - name: Stop and remove old container (if any)
      shell: docker rm -f {{ container_name }} || true

    - name: Run new container
      shell: docker run -d --name {{ container_name }} -it --restart unless-stopped {{ docker_image }}:{{ docker_tag }}
